<a href="https://colab.research.google.com/github/vohai2003/pythonproject/blob/main/BTTL1_Vector_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy

Khởi tạo vector hàng v

In [2]:
v = numpy.array([1,2,3,4,5])

Khởi tạo vector cột w

In [3]:
w = numpy.array([1,2,3,4,5]).reshape((5,1))

Biểu diễn số chiều của v và w

In [4]:
print("v=\n",v)
print("w=\n",w)

v=
 [1 2 3 4 5]
w=
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
print("Shape of v: ",v.shape)
print("Shape of w",w.shape)

Shape of v:  (5,)
Shape of w (5, 1)


Tạo ma trận ghép u và w

In [9]:
X = numpy.column_stack((v,w))
print("X=\n",X)

X=
 [[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]


Tạo ma trận X

In [10]:
X = numpy.array([[1,2,3,4,5],[6,7,8,9,2],[4,5,7,2,1]])

Nhân X với v,w

In [12]:
Xv = numpy.dot(X,v)
print("Xv=\n",Xv)
Xw = numpy.dot(X,w)
print("Xw=\n",Xw)

Xv=
 [55 90 48]
Xw=
 [[55]
 [90]
 [48]]


Khi thực hiện $X⋅v$ cho kết quả là một vector hàng \
Khi thực hiện $X\cdot w$ cho kết quả là một vector cột

Tìm ma trận chuyển vị $X^T$

In [13]:
XT = X.T
print("XT=\n",XT)

XT=
 [[1 6 4]
 [2 7 5]
 [3 8 7]
 [4 9 2]
 [5 2 1]]
